apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{.Values.deployment.namespace}}
  labels:
    app: {{.Values.label}}
  name: {{.Values.deployment.name}}
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.label }}
    spec:
      containers:
        - name: {{ .Values.deployment.containername }}
          image: "{{ .Values.deployment.image }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.targetPort }}

---
apiVersion: v1
kind: Service
metadata:
  namespace: {{.Values.deployment.namespace}}
  labels:
    app: {{ .Values.label }}
  name: {{ .Values.service.name }} 
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.label }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}